name: autofix.ci

on:
  pull_request:
    branches-ignore:
      - 'renovate/**'
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  apply:
    name: Apply automated fixes
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'renovate[bot]' && ! contains(github.event.head_commit.author.name , 'renovate[bot]') && ! contains(github.event.head_commit.message , 'chore(release)') }}
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: Setup toolchains
        uses: jdx/mise-action@9dc7d5dd454262207dea3ab5a06a3df6afc8ff26 # v3.4.1
      - name: Setup Socket Firewall
        uses: SocketDev/action@4337a545deecc20f19a909e52db7a2f6ba292f42 # v1.2.0
        with:
          mode: firewall
      - name: Optimize dependencies with @socketregistry overrides
        run: socket optimize
      - name: Format code
        run: bun biome check --write
      - name: Fix package.json
        run: bun syncpack fix
      - name: Format package.json
        run: bun syncpack format
      - name: Update package lock file
        run: sfw bun install
      - name: Submit autofix
        uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27 # v1.3.2
        with:
          fail-fast: false
