name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  npm:
    name: NPM
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup toolchains
        uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3.6.1
      - name: Setup Aikido Safe Chain
        run: curl -fsSL https://github.com/AikidoSec/safe-chain/releases/latest/download/install-safe-chain.sh | sh -s -- --ci
      - name: Install Dependencies
        run: bun ci
      - name: Update npm
        run: npm install -g npm@latest
      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@6a0a831ff30acef54f2c6aa1cbbc1096b066edaf # v1.7.0
        id: changesets
        with:
          publish: bun release
          commitMode: 'github-api'
          title: 'Release new version'
          commit: 'chore(release): bump version package'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to JSR
        run: |
          bun tools/jsr.ts
          bunx jsr publish --allow-dirty
        if: steps.changesets.outputs.published == 'true'
